set_property SRC_FILE_INFO {cfile:{C:/Users/felip/OneDrive/rea de Trabalho/UNB/3 Semestre/PED/porta_not/porta_not.srcs/constrs_1/imports/PED/Basys3_Master.xdc} rfile:../../../porta_not.srcs/constrs_1/imports/PED/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {a}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {s}]
